## Makefile
##
## Copyright (C) 2011 Rodrigo Rodrigues da Silva
##
## This file is part of dabusb-fw.
##
## dabusb-fw is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 2 of the License, or
## (at your option) any later version.
##
## dabusb-fw is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty
## of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
## See the GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

all:
	d52 dabusb_fw.bin 

clean:
	rm dabusb_fw.bin
